// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhAEpyuvI6oJzqPUan4Mi7SRj5w6nWFuk',
    appId: '1:484243280322:web:9a7eb9548363f225f4c65b',
    messagingSenderId: '484243280322',
    projectId: 'inspireme-8f886',
    authDomain: 'inspireme-8f886.firebaseapp.com',
    storageBucket: 'inspireme-8f886.firebasestorage.app',
    measurementId: 'G-46EPWMZ3YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Q43DJMzL0g8E5xkphG2is6ywbHCHY8Q',
    appId: '1:484243280322:android:85b0db96d7cd6c98f4c65b',
    messagingSenderId: '484243280322',
    projectId: 'inspireme-8f886',
    storageBucket: 'inspireme-8f886.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnc_9SE6Ayb8C6FWX4-sXggJViOxExbxo',
    appId: '1:484243280322:ios:0119be6fbf317d55f4c65b',
    messagingSenderId: '484243280322',
    projectId: 'inspireme-8f886',
    storageBucket: 'inspireme-8f886.firebasestorage.app',
    iosBundleId: 'com.example.inspireme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnc_9SE6Ayb8C6FWX4-sXggJViOxExbxo',
    appId: '1:484243280322:ios:0119be6fbf317d55f4c65b',
    messagingSenderId: '484243280322',
    projectId: 'inspireme-8f886',
    storageBucket: 'inspireme-8f886.firebasestorage.app',
    iosBundleId: 'com.example.inspireme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhAEpyuvI6oJzqPUan4Mi7SRj5w6nWFuk',
    appId: '1:484243280322:web:5318ac27fa94abe6f4c65b',
    messagingSenderId: '484243280322',
    projectId: 'inspireme-8f886',
    authDomain: 'inspireme-8f886.firebaseapp.com',
    storageBucket: 'inspireme-8f886.firebasestorage.app',
    measurementId: 'G-LWT7EL8Z1T',
  );
}
